# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r:
  - oldrel
  - release
  - devel
os:
  - osx
  - linux
matrix:
    exclude:
    - r: devel
      os: osx
repos:
  CRAN: https://cran.r-project.org
  
